### ISSUE TITLE
Issue with docs/tasks/policy-enforcement/rate-limit/index.md: documentation and YAML seem to mismatch

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#10122]
"This adds rate limit actions for any route from a virtual host named *.80."

But the envoyfilter has nothing about "80":
```yaml
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: ""
            route:
              action: ANY
```
cc @kyessenov
