### ISSUE TITLE
Observability Best Practices: example recording rules do not record TCP traffic

### ISSUE THREAD

**Issue by seanwelsh** [istio/istio.io#10311]
In Observability Best Practices (../docs/ops/best-practices/observability/#workload-level-aggregation-via-recording-rules) in the example prometheus configuration, the last six recording rules refer to istio_tcp_sent_bytes_total_count, istio_tcp_sent_bytes_total_sum, istio_tcp_sent_bytes_total_bucket, istio_tcp_received_bytes_total_count, istio_tcp_received_bytes_total_sum, istio_tcp_received_bytes_total_bucket.

Following the Integrations: Prometheus Option 2: Customized scraping configurations these metrics do not exist (I cant say if they do exist if following opt 1 as I have not tried that), so the TCP sent/received bytes data does not get aggregated or scraped by the 'production' prometheus. 

However, the metrics istio_tcp_sent_bytes_total and istio_tcp_received_bytes_total do exist, so replacing the last six recording rules with something like the following is one way to address the problem:
```yaml
        - record: "workload:istio_tcp_sent_bytes_total"
          expr: |
            sum without(instance, namespace, pod_name) (istio_tcp_sent_bytes_total)

        - record: "workload:istio_tcp_received_bytes_total"
          expr: |
            sum without(instance, namespace, pod_name) (istio_tcp_received_bytes_total)
```
