### ISSUE TITLE
Code indent error in zh page,but no error in en page.

### ISSUE THREAD

**Issue by mfdefs** [istio/istio.io#10609]
https://istio.io/latest/zh/docs/tasks/security/authentication/authn-policy/#require-a-valid-token
"notRequestPrincipals " need Code indent.
```
kubectl apply -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "frontend-ingress"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: DENY
  rules:
  - from:
    - source:
      notRequestPrincipals: ["*"]
EOF
```

https://istio.io/latest/zh/docs/tasks/security/authentication/authn-policy/#require-valid-tokens-per-path
"notRequestPrincipals" and "paths: ["/headers"]" need Code indent.
```
kubectl apply -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "frontend-ingress"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: DENY
  rules:
  - from:
    - source:
      notRequestPrincipals: ["*"]
      to:
    - operation:
      paths: ["/headers"]
EOF
```
