### ISSUE TITLE
Tracing customTags doc has incorrect manifest

### ISSUE THREAD

**Issue by lgadban** [istio/istio.io#11130]
On this doc for configuring tracing: 
https://istio.io/latest/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/#installation

The following manifest has incorrect indentation which results in bad config being applied:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100.0
        max_path_tag_length: 256
        custom_tags:
          clusterID:
          environment:
            name: ISTIO_META_CLUSTER_ID
```

It should be:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100.0
        max_path_tag_length: 256
        custom_tags:
          clusterID:
            environment:
              name: ISTIO_META_CLUSTER_ID
```
