### ISSUE TITLE
Traffic Management ServiceEntry + DestinationRule example is wrong

### ISSUE THREAD

**Issue by merusso** [istio/istio.io#11396]
Page: Documentation / Concepts / Traffic Management
Section: Service entry example
URL: https://istio.io/latest/docs/concepts/traffic-management/#service-entry-example

In the ServiceEntry example on this page, the ServiceEntry is configured for HTTPS, and a DestinationRule is configured to upgrade requests to mTLS. This will result in double encryption and a client error as described in [Traffic Management Problems > Double TLS](https://istio.io/latest/docs/ops/common-problems/network-issues/#double-tls).

Since mTLS egress has some additional caveats that may be too complex for this "concepts" page (better explained [here](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-tls-origination/#mutual-tls-origination-for-egress-traffic)), it may be better to show a simpler DestinationRule example, perhaps like adjusting the TCP connect timeout.

```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ext-res-dr
spec:
  host: ext-svc.example.com
  trafficPolicy:
    connectionPool:
      tcp:
        connectTimeout: 1s
```

Thoughts?
