### ISSUE TITLE
Kubernetes Ingress manual - an outdated API version 

### ISSUE THREAD

**Issue by Bo-Zi** [istio/istio.io#12013]
Hi!

Please update the [Specifying IngressClass](https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/#specifying-ingressclass) section 

According to the [K8s Deprecated API Migration Guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingressclass-v122) :
> The networking.k8s.io/v1beta1 API version of IngressClass is no longer served as of v1.22.
>     Migrate manifests and API clients to use the networking.k8s.io/v1 API version, available since v1.19.

Using the  Kubernetes Ingress manual gives an **error**
> **the server could not find the requested resource**

Since Kubernetes 1.19 _apiVersion: networking.k8s.io/v1_ is recommended 
```yaml 
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
```

Thank you for guys  your great work!!!
