### ISSUE TITLE
Not working example for customising istio sidecar injection

### ISSUE THREAD

**Issue by adriABC** [istio/istio.io#12774]
Hi, the current example to customise the sidecar injection is not complete and therefore is not working.
The current example is as follows:

```
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
  - name: hello
    image: alpine
  - name: istio-proxy
    image: auto
    resources:
      requests:
        cpu: "100m"
    volumeMounts:
    - mountPath: /etc/certs
      name: certs
    lifecycle:
      preStop:
        exec:
          command: ["sleep", "10"]
  volumes:
  - name: certs
    secret:
      secretName: istio-certs
```

Link: https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection

However, it doesn't mention that either the sidecar.istio.io/inject label at pod level or the istio-injection label at namespace level is still needed.

Could you review it?
Thanks!
