### ISSUE TITLE
DNS Capture In Action appears wrong

### ISSUE THREAD

**Issue by mjwhale** [istio/istio.io#13059]
The page:
https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/#dns-capture-in-action

Appears to show incorrect test results for the configuration shown:

```
To try out the DNS capture, first setup a ServiceEntry for some external service:

apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-address
spec:
  addresses:
  - 198.51.100.0
  hosts:
  - address.internal
  ports:
  - name: http
    number: 80
    protocol: HTTP

```
The example configuration shows a configuration of addresses to: 198.51.100.0

However, the results in the tests shows the connection is made to 198.51.100.1, but this is not the configured address.

```
Without the DNS capture, a request to address.internal would likely fail to resolve. Once this is enabled, you should instead get a response back based on the configured address:

$ curl -v address.internal
*   Trying 198.51.100.1:80...
```

Is the example correct?
