### ISSUE TITLE
Istio Gateway resource with SIMPLE TLS

### ISSUE THREAD

**Issue by kevinetore** [istio/istio.io#13205]
Hello everyone,

I've been trying to setup my Istio Gateway resource with the following configuration (note the credentialsName option):

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gw
  namespace: {{ .Values.argocd.targetNamespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialsName: cacerts # tls secret with key/cert
    hosts:
    - "*"
```

As per the [documentation](https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings):

> For gateways running on Kubernetes, the name of the secret that holds the TLS certs including the CA certificates. Applicable only on Kubernetes. The secret (of type generic) should contain the following keys and values: key: <privateKey> and cert: <serverCert>. For mutual TLS, cacert: <CACertificate> can be provided in the same secret or a separate secret named <secret>-cacert. Secret of type tls for server certificates along with ca.crt key for CA certificates is also supported. Only one of server certificates and CA certificate or credentialName can be specified.
--

However, the istiod logs mention the following logs:

```
info	validationServer	configuration is invalid: 2 errors occurred:
	* SIMPLE TLS requires a server certificate
	* SIMPLE TLS requires a private key
```

I did come across the following [validation code ](https://github.com/istio/istio/blame/72683f6bb7e7e9d3f95b11293dd97cc8eb13aa66/pilot/pkg/model/validation.go#L499-L523) which checks on the supplied tls options. However, this was quite old so I'm not sure if the implementation is still in place.

When adding both options:

```
tls:
      mode: SIMPLE
      serverCertificate: "random"
      privateKey: "string"
      credentialsName: cacerts
```

istiod then accepts the resource, but "removes" the credentialsName option and leaves us with:

```
...
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        privateKey: string
        serverCertificate: random
```

<br class="Apple-interchange-newline">
