### ISSUE TITLE
ServiceAccount istiod not found

### ISSUE THREAD

**Issue by seaurching** [istio/istio.io#13229]
To install istio with changed namespace to 'earth-mesh-system', there aren't pod to create. With show the `kubectl describe rs -n earth-mesh-system  istiod-78c9cf45fb` show `Warning  FailedCreate  6m18s (x19 over 17m)  replicaset-controller  Error creating: pods "istiod-78c9cf45fb-" is forbidden: error looking up service account earth-mesh-system/istiod: serviceaccount "istiod" not found`
Heare is my custom yaml, how can create the serviceaccount istiod by automatic:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    base:
      enabled: true
    cni:
      enabled: false
    ingressGateways:
    - enabled: false
      name: istio-ingressgateway
      namespace: istio-system
    - enabled: true
      name: "upay-ingress"
      namespace: "earth-mesh-system"
      label:
        ingress: "upay-ingress"
      k8s:
        service:
          type: ClusterIP
          externalIPs:
          - "10.96.249.23"
          - "10.96.249.24"
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: http2
            port: 80
            targetPort: 80
          - name: https
            port: 443
            targetPort: 8443
          - name: tls
            port: 15443
            targetPort: 15443
          - name: tcp
            port: 31400
            targetPort: 31400
        resources:
          limits:
            cpu: 3000m
            memory: 4096Mi
          requests:
            cpu: 100m
            memory: 256Mi
        hpaSpec:
          maxReplicas: 4
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 480
            type: Resource
          minReplicas: 2
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: "upay-ingress"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: "upay.domain.sys"
                  operator: "In"
                  values:
                  - "yes"
                - key: "upay.project.gateway"
                  operator: "In"
                  values:
                  - "yes"
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: "ingress"
                    operator: In
                    values:
                    - "gw-appz1p-by-in"
                topologyKey: kubernetes.io/hostname
    egressGateways:
    - enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
      name: istio-egressgateway
      namespace: earth-mesh-system
    istiodRemote:
      enabled: false
    pilot:
      enabled: true
      namespace: earth-mesh-system
      k8s:
        env:
        - name: PILOT_TRACE_SAMPLING
          value: "100"
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
  hub: docker.io/istio
  meshConfig:
    enableTracing: true
    proxyListenPort: 15001
    #tcpKeepalive: false
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    accessLogFormat: ''
    enableAutoMtls: true
    h2UpgradePolicy: DO_NOT_UPGRADE
    trustDomain: "cluster.local"
    defaultConfig:
      #parentShutdownDuration: 30s
      tracing:
        zipkin:
          address: "jaeger-prod-collector.jaeger:9411"
      statusPort: 15020
    outboundTrafficPolicy:
      mode: ALLOW_ANY
    enablePrometheusMerge: true
    extensionProviders:
    - name: skywalking
      skywalking:
        port: 11800
        service: tracing.istio-system.svc.cluster.local
  tag: 1.17.2

  values:
    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
        name: istio-egressgateway
        secretVolumes:
        - mountPath: /etc/istio/egressgateway-certs
          name: egressgateway-certs
          secretName: istio-egressgateway-certs
        - mountPath: /etc/istio/egressgateway-ca-certs
          name: egressgateway-ca-certs
          secretName: istio-egressgateway-ca-certs
        type: ClusterIP
      istio-ingressgateway:
        runAsRoot: true
        autoscaleEnabled: false
        name: istio-ingressgateway
        secretVolumes:
        - mountPath: /etc/istio/ingressgateway-certs
          name: ingressgateway-certs
          secretName: istio-ingressgateway-certs
        - mountPath: /etc/istio/ingressgateway-ca-certs
          name: ingressgateway-ca-certs
          secretName: istio-ingressgateway-ca-certs
        type: LoadBalancer
    global:
      configValidation: true
      defaultPodDisruptionBudget:
        enabled: true
      defaultResources:
        requests:
          cpu: 10m
      imagePullPolicy: "IfNotPresent"
      istioNamespace: "istio-system"
      istiod:
        enableAnalysis: true
      logAsJson: false
      logging:
        level: "default:warn"
      pilotCertProvider: istiod
      proxy:
        autoInject: enabled
        clusterDomain: "cluster.local"
        componentLogLevel: misc:error
        enableCoreDump: true
        #excludeIPRanges: ""
        #excludeInboundPorts: ""
        #excludeOutboundPorts: ""
        #image: proxyv2
        #includeIPRanges: '*'
        #logLevel: warning
        privileged: false
        readinessFailureThreshold: 30
        readinessInitialDelaySeconds: 1
        readinessPeriodSeconds: 2
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 40Mi

        statusPort: 15020
        tracer: zipkin
      sds:
        token:
          aud: istio-ca
    istiodRemote:
      injectionURL: ""
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 5
      autoscaleMin: 1
      configMap: true
      cpu:
        targetAverageUtilization: 80
    telemetry:
      enabled: true
      v2:
        enabled: true
        metadataExchange:
          wasmEnabled: false
        prometheus:
          enabled: true
          wasmEnabled: false
```
