### ISSUE TITLE
More details about the Manual deployment with the Gateway API?

### ISSUE THREAD

**Issue by mathieu-benoit** [istio/istio.io#14010]
In this doc: https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#manual-deployment, it would be really great to elaborate on the details to make this working:

- For the `Gateway` resource, could you clarify the `gatewayClassName` to use? Is it still `istio`? Or another one?
- For the ingress gateway's `Service`, should it be `ClusterIP` or `LoadBalancer`. I'm asking because I don't see how the `Gateway` will have an IP address assigned otherwise?

On a concrete example, I'm with GKE, should I have something like this:
```
gke-gateway   gke-gateway                gke-l7-gxlb   34.36.35.79                                                 True         27m
gke-gateway   istio-gateway              istio         asm-ingressgateway.gke-gateway.svc.cluster.local:80         Unknown      104s
```

**Comment by mathieu-benoit** [comment]
So I think I was able to make it working, here's how:

Manually deploy the Istio ingress gateway:
```
istio-gateway   service/istio-ingressgateway   ClusterIP
istio-gateway   deployment.apps/istio-ingressgateway
```

Deploy 2 `gtws`:
```
istio-gateway   gke-gateway                gke-l7-gxlb   xx.xx.xx.xx
istio-gateway   istio-gateway              istio         istio-ingressgateway.istio-gateway.svc.cluster.local:80
```

And then add an `HTTPRoute` to bind the 2 `gtws`:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: istio-ingressgateway
  namespace: istio-gateway
spec:
  parentRefs:
  - kind: Gateway
    name: gke-gateway
    namespace: istio-gateway
  rules:
  - backendRefs:
    - kind: Service
      name: istio-ingressgateway
      port: 80
```
