### ISSUE TITLE
Untaint controller needs documentation 

### ISSUE THREAD

**Issue by bleggett** [istio/istio.io#15003]
The untaint controller (designed to allow people to work around corner cases where new nodes are created and pods are scheduled on those nodes before our `istio-cni` node agent is scheduled on those nodes was added in https://github.com/istio/istio/pull/48818

However, we have no docs for it.

https://github.com/istio/istio/issues/50660

**Comment by ayushrakesh** [comment]
@bleggett I want to work on this issue. Please assign to me.

**Comment by fatgit** [comment]
I setup isitio in ambient mode
```
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: ambient
    helm:
      values: |
        istiod:
          defaults:
            pilot:
              taint:
                enabled: true
    targetRevision: '1.23.2'
```
**_pilot.taint.enabled:true_** helm value adds only
```
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["patch"]
```
to _istiod-clusterrole_

but this configuration doesn't remove 
```
startupTaints:
   - key: cni.istio.io/not-ready
   effect: NoExecute
```
from a node after the start.
Can I ask right helm value config?

**Comment by kirann-hegde** [comment]
@fatgit Were you able to get this working?
I cannot seem to get it working either.

@ilrudie @yuval-k Could one of you kindly advice? I am using Istio 1.25.1

Here is my helm chart configuration as part of an ArgoCD application:

```
- chart: istiod
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.25.1
      helm:
        releaseName: istiod
        values: |
          profile: ambient
          revision: 1-25-1
          autoscaleMin: 2
          autoscaleMax: 5
          replicaCount: 2
          revisionTags: 
          - default
          resources:
            requests:
              cpu: 50m
              memory: 1024Mi
            limits:
              memory: 1024Mi
          taint:
            enabled: true
```

**Comment by ilrudie** [comment]
You also need to enable the untaint controllers feature using the `PILOT_ENABLE_NODE_UNTAINT_CONTROLLERS` environment variable. You'll have something like this:
```yaml
values:
  pilot:
    taint:
      enabled: true
      namespace: istio-system
    env:
      PILOT_ENABLE_NODE_UNTAINT_CONTROLLERS: "true"
```

namespace is optional. it should be set to the location where the istio-cni is running if you set it.

**Comment by jbilliau-rcd** [comment]
I'm trying this myself and it's not working; no taints are placed on the node at any point in time, and `Job` pods fail to come up since they try to come up before the istio-cni is ready. Here's what I have:

```YAML
pilot:
  enabled: true
  k8s:
    env:
    - name: "ENABLE_NATIVE_SIDECARS"
      value: "true"
    - name: "PILOT_ENABLE_ALPHA_GATEWAY_API"
      value: "true"
    - name: "PILOT_ENABLE_IP_AUTOALLOCATE"
      value: "true"
    - name: "ENABLE_INBOUND_RETRY_POLICY"
      value: "true"
    - name: "PILOT_ENABLE_NODE_UNTAINT_CONTROLLERS"
      value: "true"
values:
  global:
     proxy:
       resources:
         limits:
           memory: 512Mi
         requests:
           cpu: 100m
           memory: 96Mi
  pilot:
    taint:
      enabled: true
      namespace: istio-system
```

Is that the right spot for `pilot.taint`? Or should it be under `values.global`? Right now I have it lined up WITH `global`, not under it. None of this makes sense though, since I thought Helm `values` was deprecated and all features/variables were being moved to the main `spec`
