### ISSUE TITLE
tabset partial breaks mirroring task page

### ISSUE THREAD

**Issue by find-arka** [istio/istio.io#15689]
Starting from [here](https://istio.io/latest/docs/tasks/traffic-management/mirroring/#creating-a-default-routing-policy) the yamls have incorrect indentation currently. Copying and pasting the same leads to `error converting YAML to JSON` error messages.

![Screenshot 2024-09-13 at 10 02 42 PM](https://github.com/user-attachments/assets/0eccdfbf-965b-4eb8-a0ad-1e0c9b8dee3e)

## Istio APIs updated

Section 1

```bash
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin
  http:
  - route:
    - destination:
        host: httpbin
        subset: v1
      weight: 100
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: httpbin
spec:
  host: httpbin
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
EOF
```

Section 2

```bash
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin
  http:
  - route:
    - destination:
        host: httpbin
        subset: v1
      weight: 100
    mirror:
      host: httpbin
      subset: v2
    mirrorPercentage:
      value: 100.0
EOF
```

## Gateway API updated

Section 1

```bash
kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: httpbin-v1
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: httpbin
    version: v1
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-v2
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: httpbin
    version: v2
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: httpbin
    port: 8000
  rules:
  - backendRefs:
    - name: httpbin-v1
      port: 80
EOF
```

Section 2

```bash
kubectl apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: httpbin
    port: 8000
  rules:
  - filters:
    - type: RequestMirror
      requestMirror:
        backendRef:
          name: httpbin-v2
          port: 80
    backendRefs:
    - name: httpbin-v1
      port: 80
EOF
```

**Comment by craigbox** [comment]
https://github.com/istio/istio.io/pull/15700#issuecomment-2361117293 reflects the actual problem

**Comment by craigbox** [comment]
The eventual cause of the error is `strip_indent.html`. 

The partial gets the input:

```
    <pre><code class='language-bash' data-expandlinks='true' data-repo='istio' >$ kubectl apply -f - &lt;&lt;EOF
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
    - httpbin
  http:
  - route:
    - destination:
        host: httpbin
        subset: v1
      weight: 10
```

It looks at the first line and says "I have to remove 4 spaces, which it dutifully does, from any line that is indented by four spaces.

```
<pre><code class='language-bash' data-expandlinks='true' data-repo='istio' >$ kubectl apply -f - &lt;&lt;EOF
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
- httpbin
```

Notes:
- `strip_indent` has already been called by the `code_blocks.html` partial to render the ``{{ text bash }}` block
- when called by `tabset.html`, `strip_indent` is being called on _the entire content of the tab_
