### ISSUE TITLE
authorization policies problem

### ISSUE THREAD

**Issue by liuliluren** [istio/istio.io#16586]
Find something strange in https://istio.io/latest/docs/ambient/getting-started/enforce-auth-policies

I follow the way it tells me but it didn't work.

If I configure the L4 ap like it tells me below:
```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
name: productpage-ztunnel
namespace: default
spec:
selector:
matchLabels:
app: productpage
action: ALLOW
rules:

from:
source:
principals:
cluster.local/ns/default/sa/bookinfo-gateway-istio
cluster.local/ns/default/sa/waypoint
```
then my curl application cant curl to productpage application

After asking AI for help, it tell me add one principal below:
**cluster.local/ns/default/sa/curl**

then my final L4 configure yaml is:
```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: productpage-ztunnel
  namespace: default
spec:
  selector:
    matchLabels:
      app: productpage
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/default/sa/bookinfo-gateway-istio
        - cluster.local/ns/default/sa/waypoint
        - cluster.local/ns/default/sa/curl
```

Finally, it can run as the tutorial shows

It seems like only when I add principals in ztunnel-L4, my waypoint-L7 confguration could work.That's way I fell strange since I didnt find principals that allow curl application in ztunnel-L4,in the tutorial it just allow sa/bookinfo-gateway-istio and sa/waypoint.

Is it because I haven't figured out the flow order of request traffic? Is my curl request sent first by istio's control plane to waypoint at L7 or to ztunnel at L4?
