### ISSUE TITLE
Issue with docs/tasks/traffic-management/secure-ingress/index.md

### ISSUE THREAD

**Issue by mabushey** [istio/istio.io#2487]
This page goes into massive detail on generating and applying a cert. I have a wildcard cert in cert manager (AWS). With plain kubernetes I use:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: project-stg
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:773610485572:certificate/0e9bbb7b-27f2-43c6-a93f-4efb8a3e6a33"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
```

Why does istio have be so insanely more complex to do the same thing? Can istio ingress work as simple as kubernetes for this?
