### ISSUE TITLE
Default mutual TLS setting is unclear in documentation

### ISSUE THREAD

**Issue by m-eaton** [istio/istio.io#2542]
When no MeshPolicy is defined, mTLS is disabled in the cluster by default.

While the default behavior is implied by explaining how to enable mTLS for the cluster with a MeshPolicy (see [Policy Storage Scope](https://istio.io/docs/concepts/security/#policy-storage-scope) and [Globally enabling Istio mTLS](https://istio.io/docs/concepts/security/#policy-storage-scope)), the default behavior is not explicitly documented. This is important information that would further clarify the use of the MeshPolicy resource.

**Comment by Niksko** [comment]
I'm happy to take this on

**Comment by BLaurenB** [comment]
It would be similarly helpful to document 'disabled' settings for Authentication Policies as well. While probably not common, a user can create a policy like this to allow only disabled traffic.
```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "svc-scope-disabled"
spec:
  targets:
    - name: details
  peers:
  - mtls:
```
 or 
```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "default"
spec:
```
If a user implements either of these policies (or any policy without a defined peers section) any traffic that tries to initiate an mTLS handshake will be rejected.

**Comment by Niksko** [comment]
@BLaurenB I get different results from you when applying your yaml.

```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "svc-scope-disabled"
spec:
  targets:
    - name: details
  peers:
  - mtls:
```

When I apply this, if I do a `kubectl get policy svc-scope-disabled -o yaml` the output shows `mtls: null`, however if I use `istioctl authn tls-check` it shows that the server only accepts `mTLS`.

After a bit of digging, it turns out this is documented at the bottom of this section: https://istio.io/docs/concepts/security/#transport-authentication

However if I apply

```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "default"
spec:
```

`istioctl authn tls-check` shows the server only accepting HTTP.

Seems like this is what needs documenting. It's hinted at in the second example on the authentication policy reference page (here: https://istio.io/docs/concepts/security/#transport-authentication), but it could serve to be more explicit.

Happy to work on this later today, I'll reference this issue in the PR, however it seems like it could well remain separate to documenting omission of a mesh policy as disabling mTLS
