### ISSUE TITLE
Query on namespace used in https://istio.io/docs/tasks/security/mutual-tls/

### ISSUE THREAD

**Issue by pasanbox** [istio/istio.io#2877]
The command given under "To illustrate the case when there are conflicts, add a service-specific destination rule" uses the namespace "bar". But everything in the example is using the "default" namespace. Is this a typo or something intentional?

```
cat <<EOF | istioctl create -n bar -f -
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "bad-rule"
spec:
  host: "httpbin.default.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
EOF
```
