### ISSUE TITLE
Extend traffic policy example for istio.networking.v1alpha3

### ISSUE THREAD

**Issue by corey-aloia** [istio/istio.io#3120]
First of all, great documentation!

It took me some minutes to realize that when creating the following destinationrule, it disables mtls for communication with the service:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-stickiness
  namespace: namespace
spec:
  host: istio-stickiness.namespace.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        useSourceIp: true
```

And it should have been:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-stickiness
  namespace: namespace
spec:
  host: istio-stickiness.namespace.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        useSourceIp: true
    tls:
      mode: ISTIO_MUTUAL
```

If think if the examples here had this extra line, it would make it a bit clearer. Either that, or have it mentioned somewhere on this page as a reminder that this will override any wildcard destination rules which may be defined (for example, when installing istio via helm with mtls enabled)

Regards,
Corey

**Comment by frankbu** [comment]
Can you be more specific about which document you think could use this?

The issue is covered in the [troubleshooting guide](https://preliminary.istio.io/help/ops/traffic-management/troubleshooting/#503-errors-after-setting-destination-rule) and some of the tasks include a note [like this](https://preliminary.istio.io/docs/tasks/traffic-management/circuit-breaking/#configuring-the-circuit-breaker).

Also, in Istio 1.1, using TLS [permissive mode](https://preliminary.istio.io/docs/concepts/security/#permissive-mode) should help avoid this problem.

**Comment by frankbu** [comment]
I think there's only so much we can do in the docs about this, but it does seem like one of the worst gotchas in the networking config model. I'm wondering how we can make it clear immediately when this kind of miss-configuration is applied.

This is sort of related to the UX issue of how do users find out what options are configure in their mesh". If we can tell them that, we can also warn them about this kind of bad destination rule.

**Comment by esnible** [comment]
Istio's DestinationRule doesn't have a default of "don't override the default".

From the point of view of docs, it might make sense to put comments into the samples.  For example, in _samples/bookinfo/networking/destination-rule-all.yaml_ we could say at the top:

```
# Note: These rules are for deployments without mTLS.  If your cluster uses mTLS use destination-rule-all-mtls.yaml
```

We could put additional comments near the rules themselves, for example:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productpage
  # this sample has no namespace, use `--namespace <ns>` to apply
spec:
  host: productpage
  trafficPolicy:
    # UNCOMMENT IF USING mTLS!
    # tls:
    #   mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      # select pods with label `version=v1`
      version: v1
```
