### ISSUE TITLE
Document capability of `istioctl validate` command

### ISSUE THREAD

**Issue by askmeegs** [istio/istio.io#3216]
Currently the examples for istioctl validate: https://preliminary.istio.io/docs/reference/commands/istioctl.html#istioctl-validate%20Examples 

Are not descriptive. Should document 
1) what the istioctl validate checks against (the object schema for the provided YAML) 
2) the limits of this command / what it does not check.

**Comment by esnible** [comment]
This is being discussed at https://discuss.istio.io/t/configuration-validation/738/4

Note: istioctl validate doesn't currently validate mixer types; for example `istioctl validate -f samples/https/nginx-app.yaml` shows `Error: error validating resource (/v1, Kind=Service Name=my-nginx Namespace=): mixer API validation is not supported`

It might be worthwhile to create an Issue in istio/istio requesting more validation.

`istioctl validate` will validate unknown fields, e.g.
```
cat <<EOF | istioctl validate -f -
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productpage
spec:
  host: productpage
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL_TYPO
  subsets:
  - name: v1
    labels:
      version: v1
EOF
```
will show a message.

It will validate the .spec; for example

```
cat <<EOF | istioctl validate -f -
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productpage
spec:
  host: productpage
  trafficPolicy:
  tls:
    mode: ISTIO_MUTUAL_TYPO
  subsets:
  - name: v1
    labels:
      version: v1
EOF
```

It doesn't validate unexpected top-level keys.  For example

```
cat <<EOF | istioctl validate -f -
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productpage
unexpected_junk:
   still_more_junk:
spec:
  host: productpage
  subsets:
  - name: v1
    labels:
      version: v1
EOF
```

This is a problem for users, and it bit you, because you moved something from .spec to the top level.  The thing that was moved was optional in .spec, and ignored at the top level, so no message was created.
