### ISSUE TITLE
zh: web site private view issue

### ISSUE THREAD

**Issue by Sanbornzhang** [istio/istio.io#3265]
error-url: https://istio.io/zh/docs/tasks/traffic-management/ingress/#使用浏览器访问-ingress-服务
code:
```
cat <<EOF | istioctl replace -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
    http:
 - match:
    - uri:
        prefix: /headers
    route:
    - destination:
        port:
          number: 8000
        host: httpbin
EOF

```
`VirtualService`  `spec.gateways[*].http` should be `spec.gateways.http` 
route:  istio.io/content_zh/docs/tasks/traffic-management/ingress/index.md
