### ISSUE TITLE
Replace VirtualServices for egress traffic by ServiceEntry Endpoints

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio.io#3312]
Direct traffic thru egress gateway by using endpoints:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  endpoints:
  - address: www.google.com
    network: external
  - address: istio-egressgateway.istio-system.svc.cluster.local
```

**Comment by vadimeisenbergibm** [comment]
@ibm-jason Could you please handle this is issue?
cc @linsun @rshriram

**Comment by ibm-jason** [comment]
@vadimeisenbergibm sure thing.

**Comment by ibm-jason** [comment]
/cc @vadimeisenbergibm 

I've taken a look at the documentation and identified these areas where VirtualServices have been defined for egress traffic:

- https://preliminary.istio.io/docs/examples/advanced-gateways/egress-gateway/#egress-gateway-for-http-traffic
  - Egress gateway for HTTP traffic, Step 4
  - Egress gateway for HTTPS traffic, Step 3
- https://preliminary.istio.io/docs/examples/advanced-gateways/egress-gateway-tls-origination/
  - Perform TLS origination with an egress gateway, Step 4
  - Deploy a mutual TLS server, Step 6
  - Configure mutual TLS origination for egress traffic, Step 2

Are there any other places in the documentation that I haven't identified?

**Comment by vadimeisenbergibm** [comment]
@ibm-jason Note that VirtualServices are redundant only if they do not rewrite the port.

In https://preliminary.istio.io/docs/examples/advanced-gateways/egress-gateway-tls-origination/
* Perform TLS origination with an egress gateway, Step 4 - rewrite port 80 to 443

**Comment by andraxylia** [comment]
@ibm-jason I maked this as a P0, please let me know if you are working on this for 1.1.

**Comment by ibm-jason** [comment]
@andraxylia Yes, I am working on this for 1.1.

**Comment by vadimeisenbergibm** [comment]
@rshriram @ibm-jason @frankbu @esnible @linsun I have reservations regarding this issue. Let me explain the situation:

There are two incompatible types of egress gateways, the old one and the new one. The new one has `ISTIO_META_REQUESTED_NETWORK_VIEW: “external”` environment variable set. The old one is configured by ServiceEntry + VirtualServices, and most of the examples with Egress Gateway use the old egress gateway. The new one is configured by ServiceEntry with endpoints, the multicluster example with gateway connectivity uses the new one, see https://preliminary.istio.io/docs/examples/multicluster/gateways/#send-remote-cluster-traffic-using-egress-gateway. The old gateway is deployed by using values.yaml, the new gateway is deployed by using values-istio-multicluster-gateways.yaml.

The two different styles of the gateways will not understand configurations of one another and will fail if configured in a different style. Using two different gateway styles can cause users confusion and problems with configuration, not working as expected. 

I propose the following:
1. To a use a single style of egress gateway, both for multicluster and for egress traffic control to external services. It is now possible, especially since now it is possible to direct multicluster traffic through 443 port (I work on https://github.com/istio/istio/issues/12224).
2. To check if we can switch to the new gateway style in all the egress examples. If we cannot, stick to the old style.
3. If we can switch to the new gateway style in all the examples now, consider to switch to it in 1.2 and not in 1.1.

**Comment by linsun** [comment]
+1 on switch to the new gateway style.  our egress gateway is confusing enough - anything that can simplify it, i'm all in favor of it.

**Comment by linsun** [comment]
for 1.1, i think that is p0 is that  we have docs updated for this - "vs is no longer needed when using service entry to allow outbound traffic".  cc @andraxylia

**Comment by vadimeisenbergibm** [comment]
@ibm-jason Please check that the endpoints can be used in *all the cases*. Please remember to use the `ISTIO_META_REQUESTED_NETWORK_VIEW: “external”` annotation in the deployment of the egress gateway. To set the annotation, use the following values snippet:
```
gateways:
  istio-egressgateway:
    env:
      # Needed to route traffic via egress gateway if desired.
      ISTIO_META_REQUESTED_NETWORK_VIEW: "external"
```

or set the value of `gateways.istio-egressgateway.env.ISTIO_META_REQUESTED_NETWORK_VIEW` in `helm template`.
