### ISSUE TITLE
Conditional Rate Limits example does not work

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio.io#3340]
Logging in as a user to explore the conditional rate limits section of the Rate Limit task does not produce expected results. The rate limits are still applied to the logged-in user.

I believe this is because the bookinfo app doesn't send a "cookie" header with a "user=" field (instead, it looks like it is "session=".

Headers taken from a debug instance:

```
request.headers               : stringmap[x-b3-traceid:136ae80c55d166952399c1cf1a91441f accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8 dnt:1 cookie:session=eyJ1c2VyIjoiamFzb24ifQ.D1CMew.g1iNqc64Yr5qvYnkDQNk9XqAnXg :path:/productpage accept-encoding:gzip, deflate upgrade-insecure-requests:1 x-request-id:280ec4f9-f29e-421a-bb7f-e3f623231631 user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 cache-control:max-age=0 content-length:0 x-b3-spanid:2399c1cf1a91441f x-envoy-internal:true x-forwarded-proto:http x-forwarded-for:10.0.1.1 :authority:35.188.74.137 x-b3-sampled:0 accept-language:en-US,en;q=0.9 :method:GET]
```

**Comment by douglas-reid** [comment]
Indeed, editing the rule to be:

```
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  actions:
  - handler: handler.memquota
    instances:
    - requestcount.quota
  match: match(request.headers["cookie"], "session=*") == false
```

works.
