### ISSUE TITLE
Update docs to reflect using hosts for non-HTTP protocols, i.e. mongo, in Istio 1.0.6

### ISSUE THREAD

**Issue by svargascsod** [istio/istio.io#3600]
Currently docs, https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry,  state that "[f]or non-HTTP protocols such as mongo/opaque TCP/even HTTPS, the hosts will be ignored". However we are able to configure our service entry to connect to our atlas mongo instance hosted on GCP using hostnames as follows:
````
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mongo
spec:
  hosts: 
  - xxx-xxx.gcp.mongodb.net
  ports:
  - number: 27017
    name: mongodb
    protocol: MONGO
  resolution: NONE
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mongo
spec:
  hosts:
  - xxx-xxx.gcp.mongodb.net
  tls:
  - match:
    - port: 27017
      sni_hosts:
      - gcp.mongodb.net
    route:
    - destination:
        host: gcp.mongodb.net
        port:
          number: 2701
      weight: 100
````
