### ISSUE TITLE
wrong n2-k8s-config file

### ISSUE THREAD

**Issue by olegchorny** [istio/istio.io#3690]
source: https://preliminary.istio.io/docs/examples/multicluster/split-horizon-eds/

by some reason this set of commands doesn't apply the filter by context
```
CLUSTER_NAME=$(kubectl --context=$CTX_CLUSTER2 config view --minify=true -o "jsonpath={.clusters[].name}")
SERVER=$(kubectl --context=$CTX_CLUSTER2 config view --minify=true -o "jsonpath={.clusters[].cluster.server}")
SECRET_NAME=$(kubectl --context=$CTX_CLUSTER2 get sa istio-multi -n istio-system -o jsonpath='{.secrets[].name}')
CA_DATA=$(kubectl get --context=$CTX_CLUSTER2 secret ${SECRET_NAME} -n istio-system -o "jsonpath={.data['ca\.crt']}")
TOKEN=$(kubectl get --context=$CTX_CLUSTER2 secret ${SECRET_NAME} -n istio-system -o "jsonpath={.data['token']}" | base64 --decode)
```
as a result, when we generate the n2-k8s-config file, it's populated by wrong values which lead to unsuccessful configuration of the entire setup.
```
cat <<EOF > n2-k8s-config
apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority-data: ${CA_DATA}
      server: ${SERVER}
    name: ${CLUSTER_NAME}
contexts:
  - context:
      cluster: ${CLUSTER_NAME}
      user: ${CLUSTER_NAME}
    name: ${CLUSTER_NAME}
current-context: ${CLUSTER_NAME}
users:
  - name: ${CLUSTER_NAME}
    user:
      token: ${TOKEN}
EOF
```
Can someone double check it? 
Thanks.
