### ISSUE TITLE
Issue with blog/2019/custom-ingress-gateway/index.md

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio.io#4590]
Guide never uses the LE cert's secret `istio-customingressgateway-certs` or even enables SDS. The Gateway references the default volume mount for `ingressgateway-certs`.

**Comment by incfly** [comment]
Reopen per https://github.com/istio/istio/issues/19111#issuecomment-557169619

@JimmyCYJ could you take a look to quickly determine if this requires some doc change or intended behavior?

**Comment by JimmyCYJ** [comment]
@incfly Thanks for letting me know. This blog was posted before ingress SDS was ready and shipped with 1.1, it is not for ingress SDS, but for file-mount approach.

The cert-manager creates ingress key/cert and save them into k8s secret ```istio-customingressgateway-cert```.

The blog asked user to deploy ingress gateway using a provided yaml file at step 6 in [Configuring the custom ingress gateway](https://archive.istio.io/v1.1/blog/2019/custom-ingress-gateway/#configuring-the-custom-ingress-gateway), that yaml file replaces the default ingress secret with the custom ingress secret in volume mount.
```
      - name: ingressgateway-custom-certs
        secret:
          defaultMode: 420
          optional: true
          secretName: istio-customingressgateway-certs
```

I haven't tested in a k8s cluster following this instructions, but I think the flow of this instruction is correct.
