### ISSUE TITLE
Suggestion: task, sample, or blog for `kind: Sidecar`

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#4747]
We have a new TrafficManagement type, Sidecar, which has been documented in the istio.io reference section since March.

There is no introduction to it ... no blog article, no Traffic Management Task, no Examples/Bookinfo control-your-sidecar configuration.

I propose we add an example that makes sense in the context of Bookinfo, for example

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: test-sidecar
  namespace: default
spec:
  workloadSelector:
    labels:
      app: productpage
  egress:
  - hosts:
    - "*/details.default.svc.cluster.local"
    - "*/reviews.default.svc.cluster.local"
EOF
```

Also, https://istio.io/docs/reference/config/networking/v1alpha3/sidecar/ contains two instances of the word "ISTIOMETAINTERCEPTION_MODE" which is incorrect, some backticks are needed because of the `_`.
