### ISSUE TITLE
Misleading TLS example Policy name

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#4760]
The [lockdown to mutual TLS](https://preliminary.istio.io/docs/tasks/security/mtls-migration/#lock-down-to-mutual-tls-optional) instructions include an example:

```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "example-httpbin-permissive"
  namespace: foo
spec:
  targets:
  - name: httpbin
  peers:
  - mtls:
      mode: STRICT
```

The name of this Policy, `example-httpbin-permissive`, is extremely misleading.  Let's call it `example-httpbin-strict`.
