### ISSUE TITLE
Issue with docs/reference/config/networking/v1alpha3/virtual-service/index.html

### ISSUE THREAD

**Issue by lxjhk** [istio/istio.io#5200]
Referenced Section:

The following example on Kubernetes, routes all HTTP traffic by default to pods of the reviews service with label “version: v1”. In addition, HTTP requests with path starting with /wpcatalog/ or /consumercatalog/ will be rewritten to /newcatalog and sent to pods with label “version: v2”.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - reviews.prod.svc.cluster.local
  http:
  - name: "reviews-v2-routes"
    match:
    - uri:
        prefix: "/wpcatalog"
    - uri:
        prefix: "/consumercatalog"
    rewrite:
      uri: "/newcatalog"
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: v2
  - name: "reviews-v1-route"
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: v1

```

According to the evaluation rule,  the code block is checking if the `URL_PREFIX ==  '/wpcatalog' AND URL_PREFIX ==  '/consumercatalog'` instead of `URL_PREFIX ==  '/wpcatalog' OR URL_PREFIX ==  '/consumercatalog' `

**Comment by frankbu** [comment]
> According to the evaluation rule ...

What "evaluation rule" are you referring to?

According to `istioctl proxy-config routes`, it works as documented. It generates two routes as expected:
```
                "routes": [
                    {
                        "name": "reviews-v2-routes",
                        "match": {
                            "prefix": "/wpcatalog",
                            "caseSensitive": true
                        },
                        "route": {
                            "cluster": "outbound|9080|v2|reviews.default.svc.cluster.local",
                            "prefixRewrite": "/newcatalog",
                           ...
                    },
                    {
                        "name": "reviews-v2-routes",
                        "match": {
                            "prefix": "/consumercatalog",
                            "caseSensitive": true
                        },
                        "route": {
                            "cluster": "outbound|9080|v2|reviews.default.svc.cluster.local",
                            "prefixRewrite": "/newcatalog",
                            ...
```

Btw, AND would make no sense. How could a request ever match two different prefixes at the same time?

**Comment by lxjhk** [comment]
The description given regarding AND and OR semantics is 

> Match conditions to be satisfied for the rule to be activated. All conditions inside a single match block have AND semantics, while the list of match blocks have OR semantics. The rule is matched if any one of the match blocks succeed.

Source: https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPRoute

```
  - name: "reviews-v2-routes"
    match:
    - uri:
        prefix: "/wpcatalog"
    - uri:
        prefix: "/consumercatalog"
    rewrite:
      uri: "/newcatalog"
```
To me, the two URI conditions look like they are in a single match block and therefore should have AND semantics, which means that only when URL_PREFIX == '/wpcatalog' AND URL_PREFIX == '/consumercatalog' would the routing rule kick into effect. And this does not make sense to me.

Am I missing something here?
