### ISSUE TITLE
Issue with docs/tasks/policy-enforcement/rate-limiting/index.md for Enabling Rate Limits task

### ISSUE THREAD

**Issue by SeriyBg** [istio/istio.io#5265]
The following override does not work by default:
```
      - dimensions:
          destination: reviews
        maxAmount: 1
        validDuration: 5s
```
As long as by default the `QuotaSpecBinding` is pointed to service `productpage` looks like you have to uncomment `- service: '*'` to make the override work.

I can add create a PR that adds this clarification if you confirm this as a bug/improvement.
