### ISSUE TITLE
inject sidecar by annotation 'sidecar.istio.io/inject' to deploymentconfig

### ISSUE THREAD

**Issue by zzzhy** [istio/istio.io#5961]
I want to inject sidecar to the deploymentconfig's pods 
by using `sidecar.istio.io/inject: 'true'`, but it doesn't work, nothing injected.
the yaml likes the following:
``` yaml
apiVersion: template.openshift.io/v1
kind: Template
metadata:
   ......
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      .....
    spec:
      ports:
        .....
      selector:
        app: '${component}-${tag}'
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: '${component}-${tag}'
      name: '${component}'
    spec:
      replicas: '${replicas}'
      selector:
        app: '${component}-${tag}'
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'true'
          labels:
            app: '${component}-${tag}'
        spec:
          containers:
              ......
```
