### ISSUE TITLE
Observability: Kiali passphrase fail to set 

### ISSUE THREAD

**Issue by shamsher31** [istio/istio.io#6078]
Ref: https://istio.io/docs/tasks/observability/kiali/

When you copy and paste following command for setting username and passphrase for Kiali.

```
KIALI_USERNAME=$(read -p 'Kiali Username: ' uval && echo -n $uval | base64)
KIALI_PASSPHRASE=$(read -sp 'Kiali Passphrase: ' pval && echo -n $pval | base64)
```
This will ask for `Kiali Username` and when you enter username, it will exit and never ask you for `Kiali Passphrase`

You may forgot to set passphrase, as above step will not ask you for it. When you proceed further and try to create secret for Kiali username and passphrase.

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: $NAMESPACE
  labels:
    app: kiali
type: Opaque
data:
  username: $KIALI_USERNAME
  passphrase: $KIALI_PASSPHRASE
EOF
```
It throws error:
```
error: error parsing STDIN: error converting YAML to JSON: yaml: line 12: could not find expected ':'
```
