### ISSUE TITLE
GCP Cloud Spanner doesn't work with ServiceEntry and VirtualService

### ISSUE THREAD

**Issue by toshi0607** [istio/istio.io#6978]
I tried Fault Injection to traffic between Cloud Spanner and spanner client, but it doesn't seem to work. Are there any misconfiguration below?

# ServiceEntry for Spanner

I want to register Spanner as ServiceEntry. I applied the following manifest.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: spanner.googleapis.com
spec:
  hosts:
  - spanner.googleapis.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
```

An endpoint is `spanner.googleapis.com:443` according to the code
https://github.com/googleapis/google-cloud-go/blob/master/spanner/client.go#L41
 and proto
https://github.com/googleapis/googleapis/blob/master/google/spanner/v1/spanner.proto#L49
# VirtualService for Fault Injection

I want to add latency between Spanner and client by 3s. I applied the following manifest.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: spanner-fault
  namespace: kouzoh-echo-jp-dev
spec:
  hosts:
  - spanner.googleapis.com
  http:
  - fault:
      delay:
        percentage:
          value: 100.0
        fixedDelay: 3s
    # match:
    # - uri:
    #     prefix: "/google.spanner.v1.Spanner/"
    route:
    - destination:
        host: spanner.googleapis.com
```

`hosts` is the same as above. I tried to limit the scope of fault injection, but it doesn't affect it. Even if I commented `match` out, latency wouldn't be added.

# How to query
I deployed [spanner-cli](https://github.com/cloudspannerecosystem/spanner-cli) with sidecar. Then I executed query

```
$ kubectl exec [pod name] -it -- sh
/ # spanner-cli -p [project name] -i [instance name] -d [DB name]
Connected.
spanner> select * from echoes;
+-------+----------+
| Id    | Message  |
+-------+----------+
| 12345 | testdata |
+-------+----------+
1 rows in set (1.11 msecs)
```

I would expect the latency to be added 3 seconds.

**Comment by ezidio** [comment]
Same problem here, but with AWS:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-redirect
  namespace: dev
spec:
  hosts:
  - "amazonaws.com"
  - "*.amazonaws.com"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  - number: 80
    name: http
    protocol: HTTP
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: external-svc-redirect
  namespace: dev
spec:
  hosts:
  - "amazonaws.com"
  - "*.amazonaws.com"
  http:
  - fault:
      delay:
        fixedDelay: 10s
        percentage:
          value: 100
    route:
      - destination:
          host: "*.amazonaws.com"
        weight: 100
---
```

I tested with the command below and the delay doesn't happen:

```
kubectl exec "$WEB_FRONT_POD" -n dev -c web-front -- time curl -o /dev/null -sSI -w "%{http_code}\n" https://global.health.amazonaws.com
```
