### ISSUE TITLE
External Prometheus with Kiali stopped working after 1.5

### ISSUE THREAD

**Issue by gopisaba** [istio/istio.io#6980]
Setting the external Prometheus address URL in Kiali is stopped working after upgraded to Istio 1.5

```
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  creationTimestamp: null
spec:
  addonComponents:
    kiali:
      enabled: true
      k8s:
        replicaCount: 3
        nodeSelector:
          nodeType: mgmt
    prometheus:
      enabled: false
 ...
  values:
    kiali:
      prometheusAddr: http://prometheus-operator-prometheus.monitoring.svc.cluster.local:9090
      dashboard:
        grafanaInClusterURL: http://prometheus-operator-grafana.monitoring.svc.cluster.local
```

Though I set `prometheusAddr` as `http://prometheus-operator-prometheus.monitoring.svc.cluster.local:9090`, it still takes the default value `http://prometheus.istio-system:9090`
```
istioctl manifest generate -f istio/istio-operator.yaml |grep -A50 -B1 "kind: ConfigMap"                                                                                                                                              ─╯
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    release: istio
data:
  config.yaml: |
    istio_component_namespaces:
      grafana: istio-system
      tracing: istio-system
      pilot: istio-system
      prometheus: istio-system
    istio_namespace: istio-system
    auth:
      strategy: login
    deployment:
      accessible_namespaces: ['**']
    login_token:
      signing_key: "KzNiPkiMh3"
    server:
      port: 20001
      web_root: /kiali
    external_services:
      istio:
        url_service_version: http://istio-pilot.istio-system:8080/version
      tracing:
        url:
        in_cluster_url: http://tracing/jaeger
      grafana:
        url:
        in_cluster_url: http://prometheus-operator-grafana.monitoring.svc.cluster.local
      prometheus:
        url: http://prometheus.istio-system:9090
```
Version
```
istioctl version --remote                                                                                                                                                                                                            
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (5 proxies), 1.5.0 (1 proxies)
```
