### ISSUE TITLE
Unusual gateway selector in the documentation for EnvoyFilter 

### ISSUE THREAD

**Issue by songford** [istio/istio.io#7026]
In https://istio.io/docs/reference/config/networking/envoy-filter/, the third example, the workload selector is:
```
spec:
  workloadSelector:
    labels:
      istio: ingress-gateway
```
However, in a default installation through `istioctl`, the ingress gateway will be labelled as:
```
istio: ingressgateway
```
Notice the absence of a hyphen. 

This discrepancy could catch a reader by surprise if he/she copies the code without reading into it carefully.
