### ISSUE TITLE
Connection Refused for bookinfo example

### ISSUE THREAD

**Issue by Trojaner** [istio/istio.io#7192]
I installed istio 1.4.7 with Rancher on a bare metal server with MetalLB. Rancher uses its own nginx ingress controller on port 8080 and 8443 so it does not conflict with my istio setup. 

Here is my gateway and virtualservice configuration, slightly adjusted for https support:
```yml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  servers:
    - hosts:
      - test.example.com
      port:
        number: 80
        name: http2
        protocol: HTTP2
      tls:
        httpsRedirect: true      
    - hosts:
      - test.example.com
      port:
        number: 443
        name: https
        protocol: HTTPS		
      tls:
        credentialName: cert-example.com # This certificate exists
        mode: SIMPLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - test.example.com
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
```

My (wildcard) certificate:
```sh
$ kubectl get certificates -n istio-system
NAME                    READY   SECRET               AGE
cert-example.com   True       cert-example.com   34m
```

Services displays correct ports:
```sh
istio-system        istio-ingressgateway        LoadBalancer   10.43.246.182  REDACTED   15020:30089/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:32006/TCP,15030:31021/TCP,15031:30754/TCP,15032:31722/TCP,15443:31035/TCP   17m
```

It only works on port 80 on the *first try* (when disabling TLS redirect), after that I get connection refused when reloading the page. Port 443 always results in connection refused.

```sh
$ curl 10.43.246.182:443
curl: (7) Failed to connect to localhost port 443: Connection refused
```

There is no firewall related issue, all related ports are definetely open.
