### ISSUE TITLE
Use canonical service-based workload selector in Classify Metrics task

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio.io#7281]
I think it would be useful to start transitioning away from:

```yaml
workloadSelector:
    labels:
      app: reviews
```

for workload selection, given that Istio is transitioning to canonical service labels (and away from app).

This issue is a tracking issue for updating the example config in the task at: https://preliminary.istio.io/docs/tasks/observability/metrics/classify-metrics/
