### ISSUE TITLE
Fix incorrectly placed comment in Tracing customization task

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio.io#7287]
For: https://preliminary.istio.io/docs/tasks/observability/distributed-tracing/configurability/

There is a section for Env vars, with a suggested config of:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      tracing:
        custom_tags:
          tag_env:
            environment:                 # user-defined name
              name: <ENV_VARIABLE_NAME>
              defaultValue: <VALUE>      # optional
```

But, `environment` is not the user-defined name. Rather, `tag_env` is.

The comment should be moved to the line above.
