### ISSUE TITLE
Add instruction on how to apply the IstioOperator config in the Tracing Configurability task

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio.io#7288]
The task works as expected, but there is no guidance on how to apply the built up customization at install. This would be nice for people new to Istio, etc.

I suggest:
- Adding an example file with some options filled in
- the `istioctl` command needed

Maybe:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      tracing:
        sampling: 100.0
        max_path_tag_length: 256
        custom_tags:
          service.istio.io/canonical-name:
            environment:
              name: CANONICAL_SERVICE
              defaultValue: latest
```

and:

`istioctl manifest apply --set values.tracing.enabled=true -f tracing.yaml`

?
