### ISSUE TITLE
Issue with docs/setup/install/multicluster/shared/index.md

### ISSUE THREAD

**Issue by carolynhu** [istio/istio.io#7326]
When main-cluster and remote-cluster are not in the same network, commented out `istio-remote0-cluster.yaml`, `components` field and run `istioctl --context ${REMOTE_CLUSTER_CTX} manifest apply -f istio-remote0-cluster.yaml`. I got the following error:

```
Error: failed to apply manifests: validation errors (use --force to override):
unknown field "components" in v1alpha1.Values
```

I'm using the 1.6-latest release `istioctl` binary.

**Comment by shamsher31** [comment]
Ref: https://preliminary.istio.io/docs/setup/install/multicluster/shared/#remote-cluster

Maybe it's an indentation issue when uncommenting the `components` config.  `components`  should be aligned properly with `values`.

```yaml
cat <<EOF> istio-remote0-cluster.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      # The remote cluster's name and network name must match the values specified in the
      # mesh network configuration of the main cluster.
      multiCluster:
        clusterName: ${REMOTE_CLUSTER_NAME}
      network: ${REMOTE_CLUSTER_NETWORK}

      # Replace ISTIOD_REMOTE_EP with the the value of ISTIOD_REMOTE_EP set earlier.
      remotePilotAddress: ${ISTIOD_REMOTE_EP}

  # The istio-ingressgateway is not required in the remote cluster if both clusters are on
  # the same network. To disable the istio-ingressgateway component, uncomment the lines below.
  
  components:
   ingressGateways:
   - name: istio-ingressgateway
     enabled: false
EOF
```
As `component` is not the part of `v1alpha1.Values` API, if it is indented incorrectly inside `spec.values.components`, It will throw error that you mentioned.
