### ISSUE TITLE
White Space error in the demo.yaml profile for 1.5 and 1.6 for linux x86

### ISSUE THREAD

**Issue by Stormarov45** [istio/istio.io#7572]
The last two lines for the demo.yaml file in the /manifest/profiles location has a missing nl/cr (mising blank line) that causes kiali not to load correctly. Due to not creating a kiali demo secret.

I had this problem with both 1.5 and 1.6 on a REHL platform using the newest version of Go and KinD.  

The "values" segment of the file looks like this:
```
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi

    pilot:
      autoscaleEnabled: false

    mixer:
      adapters:
        useAdapterCRDs: false
        kubernetesenv:
          enabled: true
        prometheus:
          enabled: true
          metricsExpiryDuration: 10m
        stackdriver:
          enabled: false
        stdio:
          enabled: true
          outputAsJson: false
      policy:
        autoscaleEnabled: false
      telemetry:
        autoscaleEnabled: false

    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
      istio-ingressgateway:
        autoscaleEnabled: false
    kiali:
      createDemoSecret: true

```

When you add the the blank line like this it deploys fine

```
    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
      istio-ingressgateway:
        autoscaleEnabled: false

    kiali:
      createDemoSecret: true
```

Otherwise you get various errors that only sometimes reference a missing kiali secret and manually creating a secret doesn't help because it gets placed in the wrong location.
