### ISSUE TITLE
Issue with docs/tasks/security/cert-management/dns-cert/index.md

### ISSUE THREAD

**Issue by woodliu** [istio/istio.io#7728]
Fellow this [step](https://istio.io/latest/docs/tasks/security/cert-management/dns-cert/#before-you-begin) to install istio, but can't find the secret as expect.
Env: openshit 4.3; istio 1.6.5
This is my config file
```
# cat cni-annotations.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    cni:
      enabled: true
      namespace: kube-system
  values:
    meshConfig:
      certificates:
        - secretName: dns.example1-service-account
          dnsNames: [example1.istio-system.svc, example1.istio-system]
        - secretName: dns.example2-service-account
          dnsNames: [example2.istio-system.svc, example2.istio-system]
    cni:
      excludeNamespaces:
       - istio-system
       - kube-system
      chained: false
      cniBinDir: /var/lib/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      cniConfFileName: istio-cni.conf
    sidecarInjectorWebhook:
      injectedAnnotations:
        "k8s.v1.cni.cncf.io/networks": istio-cni
```
