### ISSUE TITLE
Install with Istioctl references citadel

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#7827]
https://preliminary.istio.io/latest/docs/setup/install/istioctl/

has a snippet:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  components:
    citadel:
      namespace: istio-citadel

```

which yields an error: `Error: failed to install manifests: unknown field "citadel" in v1alpha1.IstioComponentSetSpec:`
