### ISSUE TITLE
Issue with docs/tasks/security/authentication/authn-policy/index.md

### ISSUE THREAD

**Issue by wghdr** [istio/istio.io#8056]
```
error: unable to recognize "STDIN": no matches for kind "MeshPolicy" in version "authentication.istio.io/v1alpha1"
error: unable to recognize "STDIN": no matches for kind "Policy" in version "authentication.istio.io/v1alpha1"
```

最新的文档是1.7版本，policy和meshpolicy都已经被移除了，需要用PeerAuthentication来代替。

```yaml
kubectl apply -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: httpbin
  namespace: "foo"
spec:
  selector:
    matchLabels:
      app: httpbin
  mtls:
    mode: STRICT
EOF
```
