### ISSUE TITLE
Issue with docs/tasks/security/authentication/authn-policy/index.md

### ISSUE THREAD

**Issue by hobbytp** [istio/istio.io#8300]
Please add description for configuration descripted in https://github.com/istio/istio/issues/24082

when autoMtls enabled and the headless service has sidecar injected, user need to either enable mtls with a Destinationrule or disable the mtls required by the headless service with a PeerAuthentication as below:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: xxxx
spec:
  host: headless-service
    tls:
      mode: ISTIO_MUTUAL
```
or

```
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
spec:
  selector:
    matchLabels:
      app: headlessxxx
      version: v1
  mtls:
    mode: DISABLE 
```
nothing need to be done when sidecar is not injected in headless services and plaintext is used automatically.
