### ISSUE TITLE
Issue with docs/tasks/security/cert-management/custom-ca-k8s/index.md

### ISSUE THREAD

**Issue by Rayzhangtian** [istio/istio.io#8549]
The command will failed as below:
```
istioctl install --set profile=demo -f ./istio.yaml
This will install the Istio profile into the cluster. Proceed? (y/N) y
Error: failed to install manifests: unknown field "pilot" in v1alpha1.IstioOperatorSpec:
```

The root cause is istio.yaml missed one line
```yaml
cat <<EOF > ./istio.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:         #<<<<missing this line
    pilot:
      k8s:
        env:
        # Indicate to Istiod that we use an Custom Certificate Authority
        - name: EXTERNAL_CA
          value: ISTIOD_RA_KUBERNETES_API
        # Tells Istiod to use the Kubernetes legacy CA Signer
        - name: K8S_SIGNER
          value: kubernetes.io/legacy-unknown
EOF
```
