### ISSUE TITLE
Docs for custom gateways

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#8607]
Currently istio.io lacks docs for installing and upgrading custom ingress gateways. This has become a common scenario for users and deserve to have some dedicated docs for it.

The closest doc I can find is:  

https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#deploy-istio-egress-gateway
https://istio.io/latest/blog/2019/custom-ingress-gateway/

cc @rvennam @William-Newshutz @frankbu

**Comment by linsun** [comment]
related to #29303

**Comment by rvennam** [comment]
The closest documentation in my opinion is hidden here:
https://istio.io/latest/docs/setup/install/istioctl/#configure-gateways
"A new user gateway can be created by adding a new list entry:"

user gateway vs custom gateway could result a search issue.

**Comment by ericvn** [comment]
Some notes that could be documented:

# Create Istio operator watching istio-system (control plane with ingress gateway)
# and custom-gateways (custom gateway) namespaces
istioctl operator init --watchedNamespaces=istio-system,custom-gateways

# Create namespaces for control plane, custom gateways, and sample apps
k create ns istio-system
k create ns custom-gateways
k create ns bookinfo
k create ns websockets

# label namespaces for sample apps for auto-injection
kubectl label namespace bookinfo istio-injection=enabled
kubectl label namespace websockets istio-injection=enabled

# Create control plane
kubectl apply -f - <<EOF\napiVersion: install.istio.io/v1alpha1\nkind: IstioOperator\nmetadata:\n  namespace: istio-system\n  name: example-istiocontrolplane\nspec:\n  profile: default\nEOF\n

# Create custom gateway
k apply -f custom-ingress.yaml

# Stand up BookInfo in it's own namespace using the control plane gateway
kubectl apply -n bookinfo -f samples/bookinfo/platform/kube/bookinfo.yaml\n\n
kubectl apply -n bookinfo -f samples/bookinfo/networking/bookinfo-gateway.yaml\n\n

# Get ingress URL for BookInfo
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}'
export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT

# Verify one can access BookInfo from command line
curl -s "http://${GATEWAY_URL}/productpage" | grep -o "<title>.*</title>"


# Stand up the Websockets app using the custom gateway
kubectl apply -n websockets -f samples/websockets/app.yaml
kubectl apply -n websockets -f websockets-gateway.yaml

# Get the custom gateway URL for WebSockets
export CG_HOST=$(kubectl -n custom-gateways get service custom-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
export CG_PORT=$(kubectl -n custom-gateways get service custom-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}')
export CG_GATEWAY_URL=$CG_HOST:$CG_PORT\n\n

# Verify one can access BookInfo from command line
curl -sS "http://${CG_GATEWAY_URL}" | grep -o "<title>.*</title>"

# You can also bring up a browser window
echo $CG_GATEWAY_URL

# Then run some curls to see the browesr window update
curl -sS "http://${CG_GATEWAY_URL}/api?id=1&value=100"
curl -sS "http://${CG_GATEWAY_URL}/api?id=1&value=300"
curl -sS "http://${CG_GATEWAY_URL}/api?id=1&value=600"


custom-ingress.yaml
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: custom-ingressgateway-iop
  namespace: custom-gateways
spec:
  profile: empty
  # hub: icr.io/ext/istio
  # tag: 1.7.1 # Force the Gateway to a specific version
  components:
    ingressGateways:
      - name: custom-ingressgateway
        label:
          istio: custom-ingressgateway
        namespace: custom-gateways
        enabled: true
```


websockets-gateway.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tornado-gateway
spec:
  selector:
    istio: custom-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tornado
spec:
  hosts:
  - "*"
  gateways:
  - tornado-gateway
  http:
  - match:
    - uri:
        prefix: /
    - uri:
        prefix: /api
    route:
    - destination:
        host: tornado
      weight: 100

```
