### ISSUE TITLE
add instructions for a working https ingress with acme

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.io#868]
https://istio.io/docs/tasks/traffic-management/ingress.html
doesn't describe required host headers

**Comment by ldemailly** [comment]
working on it in
https://github.com/istio/admin-sites/pull/32

**Comment by ldemailly** [comment]
I got it all working (with several somewhat unintuitive workarounds) in the PR above and another one in fortio for redirects.

just need to add the task and examples based on it

**Comment by prune998** [comment]
did you made any progress on this ? I'm still trying to put the pieces together to get cert-manager work with istio ingress...
Thx

**Comment by ldemailly** [comment]
@prune998 it works fine, see the pr above.
(the ingress / annotations are a bit tricky, I will try to write it up but you can see it in the PR, let me know if you have any question)

**Comment by prune998** [comment]
@ldemailly I'm still not sure to understand...

For each website that needs https + Lets'Encrypt cert, I have to : 

- create a `Certificate` for the domain + other DNS names and give an **unknown** `IngressClass` name
- create a `Service` per DNS name
- create an Ingress with an `ingress.class`= istio 

Well, that's a lot of work compared to other solutions like Traefik.

So I created a `Certificate` like so : 

```
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: test-default
  namespace: default
spec:
  secretName: test-default-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: test.default.domain.ca
  dnsNames:
  - test.default.domain.ca
  acme:
    config:
    - http01:
        ingressClass: not-there
      domains:
      - test.default.domain.ca
```

Which created a pod, an ingress and a service...
I then created my own service + ingress on top of that... 

Sounds it's still not working. 
I still see `503 UH` errors in the istio-ingress pod when trying to reach the `/.well-known/acme-challenge/xxx` URL...

**Comment by ldemailly** [comment]
The acme cert-manager setup asks for all the certs at once (with multiple `dnsNames`), so the special setup for cert-manager itself is only once for all your https cert need (per cluster)

And is a 1 time thing.

See cert-manager-ingress2 in the files above to get /.well-known/acme-challenge to go through

**Comment by prune998** [comment]
I don't get it :)

Let's say I have 10 websites with 10 domain names, what you're saying is that I have to add all the 10 domain names  to a single `Certificate` entry, right ? 

I then change the DNS so my 10 domains point to the Istio Ingress IP.

Then I create 10 `services`, one for each domain name, and use the `pod` that was created by cert-manager as the selector. (this pod is running `cert-manager-acmesolver`)

Then I create one `ingress`, using Istio class in annotations, and I create 10 rules for it, one for each domain, pointing to each of the 10 services.

Is this setup right ? 

So the fact that the `istio ingress` in my setup keeps returning `503 UH` is just a bad configuration on my side..

**Comment by prune998** [comment]
and once the SSL cert is gathered and installed, I change the Ingress to send all requests (path /*) to the right `service` of each domain ?

**Comment by prune998** [comment]
got it almost working, sounds better now and I'll be able to update the doc with a walkthrough.
Except that it's still not working : 
```
istio-ingress-7f8468bb7b-nktl9 istio-ingress [2018-01-23 14:14:17.387][16][warning][upstream] external/envoy/source/server/lds_subscription.cc:68] lds: fetch failure: Failed to load certificate '/etc/istio/ingress-certs/tls.crt'
```

So Istio-ingress is looking for certs in `/etc/istio/ingress-certs/tls.crt` when the cert in stored inside a `secret` named `test-default-tls`

**Comment by ldemailly** [comment]
if you have 10 domains, you only need 1 service but you do need 10 "host" sections (well 20 actually, 10 http and 10 https)

you have to use the hardcoded secret name the ingress expect

**Comment by prune998** [comment]
OK got it working... thanks !

**Comment by prune998** [comment]
@ldemailly, I updated the `Certificate` to add another domain and it sounds that Cert-Manager did not pick up the change, so I had to kill the pod for a restart... Do you confirm this behaviour ?

Link to my blog post about my setup : https://medium.com/@prune998/istio-envoy-cert-manager-lets-encrypt-for-tls-14b6a098f289

**Comment by ldemailly** [comment]
can you share the logs of the cert-manager pod when you resent your cert.yaml ?
I haven't tried that myself but I can try

you beat me to writing it up :-) I may still write up something or at least a task here

**Comment by prune998** [comment]
OK so I just reproduced a change, like adding a new domain name to the `certificate`.
I don't know why but it went well this time. Of course, to have it working you need to create the associated `service` + `ingress`.
Then the cert is updated.
`Istio-ingress` also detected the change and reloaded itself. It's giving a little bit too much logs though : 
```
istio-ingress-7f8468bb7b-pxl94 istio-ingress ERROR: logging before flag.Parse: I0124 18:33:25.979101       1 watcher.go:123] watchFileEvents: "/etc/istio/ingress-certs//..1981_24_01_18_33_25.658936513": CREATE
istio-ingress-7f8468bb7b-pxl94 istio-ingress ERROR: logging before flag.Parse: I0124 18:33:25.979211       1 watcher.go:123] watchFileEvents: "/etc/istio/ingress-certs//..1981_24_01_18_33_25.658936513": MODIFY|ATTRIB
istio-ingress-7f8468bb7b-pxl94 istio-ingress ERROR: logging before flag.Parse: I0124 18:33:25.979284       1 watcher.go:123] watchFileEvents: "/etc/istio/ingress-certs//..data_tmp": RENAME
istio-ingress-7f8468bb7b-pxl94 istio-ingress ERROR: logging before flag.Parse: I0124 18:33:25.979382       1 watcher.go:123] watchFileEvents: "/etc/istio/ingress-certs//..data": CREATE
istio-ingress-7f8468bb7b-pxl94 istio-ingress ERROR: logging before flag.Parse: I0124 18:33:25.979419       1 watcher.go:123] watchFileEvents: "/etc/istio/ingress-certs//..1981_24_01_14_29_40.978454218": DELETE




istio-ingress-7f8468bb7b-pxl94 istio-ingress ERROR: logging before flag.Parse: I0124 18:33:35.979301       1 watcher.go:136] watchFileEvents: notifying
istio-ingress-7f8468bb7b-pxl94 istio-ingress ERROR: logging before flag.Parse: I0124 18:33:35.979790       1 agent.go:186] Received new config, resetting budget
istio-ingress-7f8468bb7b-pxl94 istio-ingress ERROR: logging before flag.Parse: I0124 18:33:35.979810       1 agent.go:261] Reconciling configuration (budget 10)
istio-ingress-7f8468bb7b-pxl94 istio-ingress ERROR: logging before flag.Parse: I0124 18:33:35.979895       1 agent.go:281] Epoch 3 starting
istio-ingress-7f8468bb7b-pxl94 istio-ingress ERROR: logging before flag.Parse: I0124 18:33:35.979923       1 config.go:49] writing configuration to /etc/istio/proxy/envoy-rev3.json
```
Envoy is deployed with otpion `-v 2`, that may be the issue. Will check the Envoy code.

So it seems to be working as expected. Maybe I made a mistake in my previous tests...

@ldemailly you definitely have to write something yourself and explain how to deploy your test scenario with Fortio. I didn't released any code myself because that's what you are doing...

**Comment by dinostheo** [comment]
Hi,

I was following your [guide](https://github.com/istio/admin-sites/commit/a40d45e019c57a3371ca0d3922b814cccc742f67), but I could not understand how the secret `istio-ingress-certs` would be created. 

Here's what I'm getting in the logs of the cert manager
```
I0309 12:48:49.472920       1 sync.go:107] Error checking existing TLS certificate: secret "istio-ingress-certs" not found
I0309 12:48:49.472967       1 sync.go:238] Preparing certificate with issuer
I0309 12:48:49.472996       1 sync.go:242] Error preparing issuer for certificate: Error getting ACME account: secret "istio-ingress-certs" not found
I0309 12:48:49.472829       1 controller.go:136] issuers controller: syncing item 'istio-system/letsencrypt-prod'
E0309 12:48:49.479123       1 sync.go:190] [istio-system/gitops-cert-prod] Error getting certificate 'istio-ingress-certs': secret "istio-ingress-certs" not found
```

Your approach have worked for both of you apparently, so I convinced that I miss some information around `istio-ingress-certs`.

**Comment by prune998** [comment]
@dinostheo I think this secret is created when installing istio... what do you see using `kubectl -n istio-system get secrets` ?

**Comment by dinostheo** [comment]
@prune998 I have quite a few secrets there, but not the one I 'm looking for

```
default-token-mbxz5                                  kubernetes.io/service-account-token   3         23h
istio-ca-secret                                      istio.io/ca-root                      2         23h
istio-ca-service-account-token-h892z                 kubernetes.io/service-account-token   3         23h
istio-ingress-service-account-token-svpfg            kubernetes.io/service-account-token   3         23h
istio-mixer-service-account-token-twblw              kubernetes.io/service-account-token   3         23h
istio-pilot-service-account-token-2gsrj              kubernetes.io/service-account-token   3         23h
istio-sidecar-injector-service-account-token-q8pst   kubernetes.io/service-account-token   3         23h
istio.default                                        istio.io/key-and-cert                 3         23h
istio.istio-ca-service-account                       istio.io/key-and-cert                 3         23h
istio.istio-ingress-service-account                  istio.io/key-and-cert                 3         23h
istio.istio-mixer-service-account                    istio.io/key-and-cert                 3         23h
istio.istio-pilot-service-account                    istio.io/key-and-cert                 3         23h
istio.istio-sidecar-injector-service-account         istio.io/key-and-cert                 3         23h
letsencrypt-prod-secret                              Opaque                                1         48m
sidecar-injector-certs                               Opaque                                2         23h
```

**Comment by ldemailly** [comment]
it gets created when it doesn’t exist / when you first start (by cert manager)

**Comment by dinostheo** [comment]
Eventually, I have it working. 
The Certificate manifest it did not create the `istio-ingress-certs` secret as I was expecting. Trying to run it one more time after everything else was created and running, it did the work.

**Comment by davidquarles** [comment]
i know there's a ton of in-flight work around `istio-ingress` right now, so i'm curious:
- how many of these workarounds will be necessary moving forward
- if there's any corresponding work that isn't captured in existing issues (we can help!)
- whether or not acme v2 / wildcard certs buy us anything in this domain

**Comment by ldemailly** [comment]
wildcard certs would simplify the setup of some multi domain with common suffix but it's not a major change, imo

**Comment by prune998** [comment]
@dinostheo I did completly re-installed Istio, and lost my setup. When re-deploying Istio and the cert-manager, I also had the issue where `istio-ingress-certs` is not created...
For the moment I created it by hand using : 

```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /tmp/tls.key -out /tmp/tls.crt -subj "/CN=foo.bar.com"
kubectl create -n istio-system secret tls istio-ingress-certs --key /tmp/tls.key --cert /tmp/tls.crt
```
Will have to investigate....

**Comment by ldemailly** [comment]
maybe the doc swat team can tackle this

**Comment by prune998** [comment]
not sure it's still valid for 0.8.0.. ?

**Comment by prune998** [comment]
For the moment I have no clue of how it's going to work with  v1alpha3 traffic management API and ingressGateway
I'm looking into it right now, but, heh, no docs right ? 😄

**Comment by prune998** [comment]
Thanks @ldemailly 
I've gone through this already but I may have missed something.
Let's say I have www.site1.com and www.site2.com, I understood that it would requite 2 `Gateways` and 2 `VirtualServices`.

Gateways : 
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: site1-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/site1.crt
      privateKey: /etc/istio/ingressgateway-certs/site1.key
    hosts:
    - "www.site1.com"
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "www.site1.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: site2-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/site2.crt
      privateKey: /etc/istio/ingressgateway-certs/site2.key
    hosts:
    - "www.site2.com"
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "www.site2.com"
```

But as soon as I deploy that, I have errors like : 

```
istio-ingressgateway-5dfc8cb677-s8v5w ingressgateway [2018-06-22 11:07:10.923][33][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:218] gRPC config for type.googleapis.com/envoy.api.v2.Listener update rejected: Error adding/updating listener 0.0.0.0_80: error adding listener '0.0.0.0:80': multiple filter chains with the same matching rules are defined
istio-ingressgateway-5dfc8cb677-s8v5w ingressgateway [2018-06-22 11:07:10.923][33][warning][config] bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener 0.0.0.0_80: error adding listener '0.0.0.0:80': multiple filter chains with the same matching rules are defined
```

So, my guess in that I should have only ONE Gateway, defining the 80 and 443 ports and listing all the possible hosts I want to allow ? 
If that's true, that also mean I can only use ONE SSL Certificate for all my domains ? 

This is pretty unclear for me now...

**Comment by prune998** [comment]
After some testing, I was able to get it working with : 
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: site1-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/site1.crt
      privateKey: /etc/istio/ingressgateway-certs/site1.key
    hosts:
    - "www.site1.com"
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "www.site1.com"

  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/site2.crt
      privateKey: /etc/istio/ingressgateway-certs/site2.key
    hosts:
    - "www.site2.com"
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "www.site2.com"
```

Meaning that : 
- I can use SNI this way
- all the SSL certificates have to be defined in the same secret named `istio-ingressgateway-certs`
- I have to modify the same `Gateway` everytime I add a new website
- updating an SSL certificate will require to restart the istio-ingressgateway pod or delete/add the website from the Gateway (I havn't tested this yet, it's juste an expectation)

For the moment I'm going to move to the `Cert Manager` part and see how to use it with Istio 0.8.0

**Comment by sekka1** [comment]
I am running into the same problem but what was propose above is not working on my cluster.  

I dont have the cert files like above so i removed the 443 endpoints and applied this:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: site1-gateway
spec:
  selector:
    istio: ingressgateway
  servers:

  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "www.site1.com"

  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "www.site2.com"
```

Looking at the `istio-ingressgateway` logs I get:
```
[2018-07-12 18:11:16.816][21][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:218] gRPC config for type.googleapis.com/envoy.api.v2.Listener update rejected: Error adding/updating listener 0.0.0.0_80: error adding listener '0.0.0.0:80': multiple filter chains with the same matching rules are defined
[2018-07-12 18:11:16.816][21][warning][config] bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener 0.0.0.0_80: error adding listener '0.0.0.0:80': multiple filter chains with the same matching rules are defined
```

Am i missing something else here?

**Comment by sekka1** [comment]
Playing around with it more, doing it this way works for me:

```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-1
spec:
  selector:
    istio: ingressgateway
  servers:

  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "www.site1.com"
    - "www.site2.com"
```

I guess you are telling it to open 1 port and listen for these hostnames on the port.

Then i thought to try this and this works also:

```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-1
spec:
  selector:
    istio: ingressgateway
  servers:

  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```
However this gateway only works in the name space I created it in and the pods for these ingresses has to be in that namespace also.

So i guess you have to create another istio inbound ingress for each namespace?  I can very well be missing some fundamental concepts here.  I tried to read all of the docs i can find about this but im not able to find a section where it tells me what I should be doing.
