### ISSUE TITLE
convert nginx rewrite regex to istio

### ISSUE THREAD

**Issue by Baitanik** [istio/istio.io#8874]
I have following nginx ingress.. which I am trying to convert to istio virtual service.
nginx :
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-control-plane
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    app: metalk8s-ui
    app.kubernetes.io/name: metalk8s-ui
    app.kubernetes.io/part-of: metalk8s
    heritage: salt
    metalk8s.scality.com/version: 2.6.0-dev
  name: metalk8s-ui-proxies-https
  namespace: metalk8s-ui
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: kubernetes-api
          servicePort: 443
        path: /api/kubernetes(/|$)(.*)
      - backend:
          serviceName: salt-api
          servicePort: 4507
        path: /api/salt(/|$)(.*)
```

I tried to convert it to vs : 
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: metalk8s-ui-proxies-https
  namespace: metalk8s-ui
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /api/kubernetes
    rewrite:
      uri: /
    route:
    - destination:
        host: kubernetes-api
        port:
          number: 443
      weight: 100
  - match:
    - uri:
        prefix: /api/salt
    rewrite:
      uri: /
    route:
    - destination:
        host: salt-api
        port:
          number: 4507
      weight: 100

```
which seems to not working properly ... 
 i tried with 
     - uri:
        regex: /api/kubernetes(/|$)(.*) ... 

but how to configure the rewrite regex ? /$2 in istio ... 
could you please help..
