### ISSUE TITLE
How to configure a service to be cluster-local 

### ISSUE THREAD

**Issue by stevenctl** [istio/istio.io#9558]
Document the use of meshConfig to restrict endpoints for a service to be pushed only to the local cluster:

```
  meshConfig:
    serviceSettings: 
      - settings:
          clusterLocal: true
        hosts:
          - "svc.ns.svc.cluster.local"
```
