### ISSUE TITLE
Issue with docs/ops/best-practices/observability/index.md

### ISSUE THREAD

**Issue by ethernoy** [istio/istio.io#9603]
Hi, the aggregation rule of Istio TCP metrics in this document seems is not referring to the latest valid set of Istio TCP metrics.

```
- record: "workload:istio_tcp_sent_bytes_total_count"
    expr: |
      sum without(instance, namespace, pod) (istio_tcp_sent_bytes_total_count)

  - record: "workload:istio_tcp_sent_bytes_total_sum"
    expr: |
      sum without(instance, namespace, pod) (istio_tcp_sent_bytes_total_sum)

  - record: "workload:istio_tcp_sent_bytes_total_bucket"
    expr: |
      sum without(instance, namespace, pod) (istio_tcp_sent_bytes_total_bucket)

  - record: "workload:istio_tcp_received_bytes_total_count"
    expr: |
      sum without(instance, namespace, pod) (istio_tcp_received_bytes_total_count)

  - record: "workload:istio_tcp_received_bytes_total_sum"
    expr: |
      sum without(instance, namespace, pod) (istio_tcp_received_bytes_total_sum)

  - record: "workload:istio_tcp_received_bytes_total_bucket"
    expr: |
      sum without(instance, namespace, pod) (istio_tcp_received_bytes_total_bucket)
```

The available Istio TCP metrics of v1.9 contains:

- istio_tcp_connections_opened_total
- istio_tcp_connections_closed_total
- istio_tcp_received_bytes_total
- istio_tcp_sent_bytes_total

The last two metrics listed above are not included in the aggregation.

I wonder if this document is outdated and should be updated? If so I am glad to help.

**Comment by ethernoy** [comment]
I double-checked the standard [Istio metrics list](https://istio.io/latest/docs/reference/config/metrics/), it only contains the TCP metrics listed above. Also the [Grafana Istio dashboard](https://grafana.com/grafana/dashboards/7636) needs to use the metric istio_tcp_received_bytes_total and istio_tcp_sent_bytes_total. I think two new entries need to be added to this aggregation list:

```yaml
- record: "workload:istio_tcp_sent_bytes_total"
   expr: "sum without(instance, namespace, pod) (istio_tcp_sent_bytes_total)"
- record: "workload:istio_tcp_received_bytes_total"
   expr: "sum without(instance, namespace, pod) (istio_tcp_received_bytes_total)"
```

Can I create a PR regarding this issue?
